#!/usr/bin/env nu

# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

# Generator project directory, relative to the repo root.
const GENERATOR_PROJECT = 'src/ThatCore.Valheim.Generator'

# Namespace the emitted constant classes live in.
const GENERATED_NAMESPACE = 'ThatCore.Valheim.Generator.Generated'

# Each source project, and whether its top-level types get internalized.
const SOURCE_PROJECTS = [
    { name: 'ThatCore', path: 'src/ThatCore' }
    { name: 'ThatCore.Valheim', path: 'src/ThatCore.Valheim' }
    { name: 'ThatCore.Shared', path: 'src/ThatCore.Shared' }
]

# The csproj whose <Version> is used to set the generators.
const VERSION_SOURCE_PROJECT = 'src/ThatCore/ThatCore.csproj'

const EXCLUDED_DIRECTORIES = ['bin', 'obj', '.vs']
const EXCLUDED_FILE_SUFFIXES = ['.g.cs', '.generated.cs', '.Designer.cs']
const EXCLUDED_FILE_NAMES = ['AssemblyInfo.cs']

# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

def get-project-version [csproj_path: string] {
    if not ($csproj_path | path exists) {
        error make { msg: $"Version source project not found: ($csproj_path)" }
    }

    let versions = (
        open $csproj_path
        | find -n <Version>
        | parse '{_}>{Value}<{_}'
        | get Value
    )

    if ($versions | is-empty) {
        error make { msg: $"No <Version> element found in ($csproj_path)" }
    }

    $versions | first
}

def get-source-files [
    project_directory: string
    excluded_directories: list<string>
    excluded_file_suffixes: list<string>
    excluded_file_names: list<string>
] {
    # glob treats a backslash as an escape, so patterns are always slash-based.
    let root = ($project_directory | str replace --all '\' '/')

    glob $"($root)/**/*.cs"
    | where { |file|
        let name = ($file | path basename)
        let segments = ($file | path relative-to $root | split row --regex '[\\/]')

        let in_excluded_dir = ($segments | any { |s| $s in $excluded_directories })
        let is_excluded_file = (
            ($name in $excluded_file_names) or
            ($excluded_file_suffixes | any { |s| $name | str ends-with $s })
        )

        (not $in_excluded_dir) and (not $is_excluded_file)
    }
    | sort --ignore-case
}

# Path-derived so that same-named files in different folders stay unique.
# src/ThatCore/Config/Toml/Writers/IntListWriter.cs
#     -> ThatCore.Config.Toml.Writers.IntListWriter.g.cs
def to-hint-name [project_name: string, relative_path: string] {
    let dotted = (
        $relative_path
        | str replace --regex '\.cs$' ''
        | str replace --all --regex '[\\/]' '.'
    )

    $"($project_name).($dotted).g.cs"
}

def to-identifier [hint_name: string] {
    let identifier = (
        $hint_name
        | str replace --regex '\.g\.cs$' ''
        | str replace --all --regex '[^A-Za-z0-9]' '_'
    )

    if ($identifier =~ '^[0-9]') { $"_($identifier)" } else { $identifier }
}

# Normalize to CRLF so the wrapper and the payload never mix line endings
# within one generated file (mixed endings make git diffs unreadable).
def normalize [] : string -> string {
    str replace --all "\r\n" "\n" | str replace --all "\n" "\r\n"
}

def update-generator-version [csproj_path: string, version: string] {
    let content = (open --raw $csproj_path | decode utf-8)

    if not ($content =~ '<Version>.*?</Version>') {
        return
    }

    let updated = ($content | str replace --all --regex '<Version>.*?</Version>' $"<Version>($version)</Version>")

    if $updated != $content {
        $updated | normalize | save --raw --force $csproj_path
        print $"  Generator version -> ($version)"
    }
}

def generate-file [
    file: string, 
    project_dir: string,
    project_name: string,
    out_dir: string
    verbose: bool
] {
    let relative_path = ($file | path relative-to ($project_dir | str replace --all '\' '/'))
    let display_path = ($project_name | path join $relative_path)

    # Verbatim string literal: the only escape is doubling the quote. No indentation semantics, unlike a raw string literal.
    let text = (open --raw $file | decode utf-8) | normalize | str replace --all '"' '""';

    let hint_name = (to-hint-name $project_name $relative_path)

    let identifier = (to-identifier $hint_name)
    let output_path = ($out_dir | path join $"($identifier).g.cs")

    let content = ([
        '// <auto-generated>'
        $"//    Produced from ($display_path | str replace --all --regex '[\\/]' '/')"
        '// </auto-generated>'
        ''
        $"namespace ($GENERATED_NAMESPACE);"
        ''
        '[SourceFile]'
        $"internal static class ($identifier)"
        '{'
        $'    internal static string HintName => "($hint_name)";'
        ''
        $'    internal static string Source => @"($text)";'
        '}'
    ] | str join "\r\n")

    $content | normalize | save --raw --force $output_path

    if $verbose {
        print $"  ($display_path)"
    }

    return $output_path
}

# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

# Emits the core sources as C# string constants inside the generator project.
def main [
    --repo-root: string     # Repo root. Defaults to the parent of the folder holding this script.
    --verbose (-v)          # Print every file as it is emitted.
] {
    let repo_root = ($repo_root | default ($env.FILE_PWD | path dirname) | path expand)
    let generator_directory = ($repo_root | path join $GENERATOR_PROJECT | path expand --no-symlink)
    let generated_directory = ($generator_directory | path join 'Generated')

    let source_version = (get-project-version ($repo_root | path join $VERSION_SOURCE_PROJECT))
    print $"Version: ($source_version)"

    # Initial cleanup
    rm --recursive --force $generated_directory
    mkdir $generated_directory
  
    # Run collection and source generation
    mut file_count = 0

    for project in $SOURCE_PROJECTS {

        let project_directory = ($repo_root | path join $project.path | path expand --no-symlink)

        if not ($project_directory | path exists) {
            error make { msg: $"Project directory not found: ($project_directory)" }
        }

        print $"Scanning and generating files for ($project.name)..."

        $file_count += get-source-files $project_directory $EXCLUDED_DIRECTORIES $EXCLUDED_FILE_SUFFIXES $EXCLUDED_FILE_NAMES
        | each { |file| generate-file $file $project_directory $project.name $generated_directory $verbose }
        | length
    }

    print $"Generated ($file_count) source files -> ($generated_directory)"

    # Version sync
    let generator_csproj = (glob $"($generator_directory | str replace --all '\' '/')/*.csproj" | first)
    update-generator-version $generator_csproj $source_version

    print $"Done.";
}
